move ssd1306 to dev-deps and bump other crates to their newest, closes #417
atsamd-rs/atsamd pull request #419
Opened 2021-03-21 03:11 UTC by olback

2021-03-21 06:41 UTC, TDHolmes approved these changes

2021-03-22 02:40 UTC, twitchyliquid64 requested changes
Looks good to go without the version bump. Thanks!

2021-03-22 02:40 UTC, twitchyliquid64 commented on boards/arduino_nano33iot/Cargo.toml
> +version = "0.5.0"
Drop this bump, we do this automatically when we run a release.

2021-03-22 22:13 UTC, twitchyliquid64 approved these changes

2021-03-22 22:13 UTC, merged